import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				<nav className="flex px-[2vw] pt-[1vh] w-full items-center justify-between fixed top-0 left-0">
					<a href="/" className="fusskia text-[2.5vh]">
						Home
					</a>
					<a href="/" className="fusskia text-[2.5vh]">
						Works
					</a>
					<a href="/" className="fusskia text-[2.5vh]">
						About
					</a>
					<a href="/" className="fusskia text-[2.5vh]">
						Contact
					</a>
				</nav>
				{children}
			</body>
		</html>
	);
}
