import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<head>
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100..900;1,100..900&family=Exo:ital,wght@0,100..900;1,100..900&family=Oswald:wght@200..700&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body className="flex flex-col w-full">
				<nav className="flex pt-[1vh] w-full items-center justify-between fixed top-0 left-0 z-99 bg-white">
					<a
						href="/"
						className="exo font-light tracking-[-1px] text-[2vh] mx-[2vw]"
					>
						Home
					</a>
					<a
						href="/featured"
						className="exo font-light tracking-[-1px] text-[2vh] mx-[2vw]"
					>
						Works
					</a>
					<a
						href="/about"
						className="exo font-light tracking-[-1px] text-[2vh] mx-[2vw]"
					>
						About
					</a>
					<a
						href="/"
						className="exo font-light tracking-[-1px] text-[2vh] mx-[2vw]"
					>
						Contact
					</a>
				</nav>
				{children}
			</body>
		</html>
	);
}
