import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body className="flex flex-col w-full">
				<nav className="flex pt-[1vh] w-full items-center justify-between fixed top-0 left-0 z-99 bg-white">
					<a href="/" className="fusskia text-[2.5vh] mx-[2vw]">
						Home
					</a>
					<a href="/" className="fusskia text-[2.5vh] mx-[2vw]">
						Works
					</a>
					<a href="/about" className="fusskia text-[2.5vh] mx-[2vw]">
						About
					</a>
					<a href="/" className="fusskia text-[2.5vh] mx-[2vw]">
						Contact
					</a>
				</nav>
				{children}
			</body>
		</html>
	);
}
